artifact_location: file:///C:/Users/karad/Desktop/face-detection-project/scripts/runs/mlflow/542642606581132255
creation_time: 1752753322709
experiment_id: '542642606581132255'
last_update_time: 1752753322709
lifecycle_stage: active
name: /Shared/Ultralytics
