artifact_location: file:///C:/Users/karad/Desktop/face-detection-project/scripts/runs/mlflow/0
creation_time: 1752753322693
experiment_id: '0'
last_update_time: 1752753322693
lifecycle_stage: active
name: Default
